Task 2 - Create MVC Template
Software-Engineering-LNU/Software-Engineering-Project-2 pull request #4
Opened 2023-03-05 17:30 UTC by SergiyVengrin

Closes #2

2023-03-22 09:53 UTC, DarkPhoeniix requested changes

2023-03-22 09:53 UTC, DarkPhoeniix commented on EmployeestWeb.DAL/Data/EmployeestWebDbContext.cs
> +        public virtual DbSet<EventMember> EventMembers { get; set; } = null!;
As we discussed earlier - we removed events from out DB. Update the code according to the last version of DB.

2023-03-22 09:53 UTC, DarkPhoeniix commented on EmployeestWeb.DAL/Data/EmployeestWebDbContext.cs
> +            modelBuilder.Entity<EventMember>(entity =>
Same as above - remove entities we are not going to use

2023-03-22 09:53 UTC, DarkPhoeniix commented on EmployeestWeb.DAL/Data/EmployeestWebDbContext.cs
> +                entity.Property(e => e.Estimation).HasColumnName("estimation");
We already have story points for the estimation - remove 'estimation field'

2023-03-22 09:53 UTC, DarkPhoeniix commented on EmployeestWeb/Properties/launchSettings.json
> +      "sslPort": 44391
Can we remove the ssl?

2023-03-27 12:10 UTC, DarkPhoeniix requested changes

2023-03-27 12:10 UTC, DarkPhoeniix commented on EmployeestWeb/Program.cs
> +            builder.Services.AddControllersWithViews();
remove the duplicate line

2023-03-27 12:10 UTC, DarkPhoeniix commented on EmployeestWeb/Program.cs
fix Sonar code smells

2023-03-27 12:10 UTC, DarkPhoeniix commented on EmployeestWeb.DAL/Data/EmployeestWebDbContext.cs
> +        public virtual DbSet<Permission> Permissions { get; set; } = null!;
Use 'default' instead of 'null!'

2023-04-01 08:39 UTC, DarkPhoeniix requested changes

2023-04-01 08:39 UTC, DarkPhoeniix commented on EmployeestWeb/Program.cs
> +            builder.Services.AddDbContext<EmployeestWebDbContext>(options =>
Does it duplicate lines 22-29? If yes, could you remove it?

2023-04-01 11:50 UTC, DarkPhoeniix approved these changes

2023-04-01 20:30 UTC, OleksiiDatsiuk approved these changes

2023-04-01 20:34 UTC, merged